#image: cypress/browsers:chrome69
#image: cypress/base:8
image: cypress/base:10

stages:
  - install
  - test

# this is a generated file
# caching node_modules folder
# https://about.gitlab.com/2016/03/01/gitlab-runner-with-docker/
cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:  
  - node_modules
  #- .npm
  - cache/Cypress
  #- .cache/Cypress
  - /root/.cache/Cypress
  - /builds/passpod/qa-test/node_modules

variables:
  npm_config_cache: /.npm
  CYPRESS_CACHE_FOLDER: /cache/Cypress

install:
  #image: cypress/browsers:chrome67
  #image: bahmutov/cypress-image
  stage: install
  tags:
    - docker

  script:
    - npm install --save-dev cypress
    - $(npm bin)/cypress verify


# we will generate the test definitions per spec bundle
# using the common definition

# Hidden job that defines an anchor named 'e2e_test_definition'
# This job will be automatically assigned "test" phase
.job_template: &e2e_test_definition
  #image: cypress/browsers:chrome67
  #image: bahmutov/cypress-image
  tags:
    - docker
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - cypress/screenshots/
      - cypress/videos/
  script:
    #- DEBUG=cypress:* $(npm bin)/cypress run --spec cypress/integration/$CI_BUILD_NAME.js --config video=false
    - $(npm bin)/cypress run --spec cypress/integration/$CI_BUILD_NAME.js

Activity_passpod:
  <<: *e2e_test_definition
    
addAttractionAndWifiToCart:
  <<: *e2e_test_definition
