#image: cypress/browsers:chrome69
#image: cypress/base:8
#image: cypress/base:10
image: kiwicom/cypress-cli

stages:
  - install
  - test

# this is a generated file
# caching node_modules folder
# https://about.gitlab.com/2016/03/01/gitlab-runner-with-docker/
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:  
  #- node_modules/
  #- .npm
  #- cache/Cypress
  #- .cache/Cypress
  #- /root/.cache/Cypress
  #- /builds/passpod/qa-test/node_modules

variables:
  #npm_config_cache: /builds/passpod/qa-test/.npm
  CYPRESS_CACHE_FOLDER: /cache/Cypress

#install:
  #image: cypress/browsers:chrome67
  #image: bahmutov/cypress-image
  #stage: install
  #tags:
  # - docker

  #script:
  #  - npm install --save-dev cypress
  #  - $(npm bin)/cypress verify


# we will generate the test definitions per spec bundle
# using the common definition

# Hidden job that defines an anchor named 'e2e_test_definition'
# This job will be automatically assigned "test" phase
.job_template: &e2e_test_definition
  #image: cypress/browsers:chrome67
  #image: bahmutov/cypress-image
  tags:
    - cypress
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - cypress/screenshots/
      - cypress/videos/
  script:
    #- pwd && ls -al
    #- ls -al /builds/passpod/qa-test/node_modules
    #- npm install --save-dev cypress
    #- DEBUG=cypress:* $(npm bin)/cypress run --spec cypress/integration/$CI_BUILD_NAME.js --config video=false
    #- $(npm bin)/cypress run --spec cypress/integration/$CI_BUILD_NAME.js
    - cypress run --spec cypress/integration/$CI_BUILD_NAME.js

activityToCart:
  <<: *e2e_test_definition

activityToCartSt:
  <<: *e2e_test_definition

addAttractionAndWifiToCart:
  <<: *e2e_test_definition

addAttractionFromItineraryToCartLogin:
  <<: *e2e_test_definition

addAttractionFromItineraryToCartLoginSt:
  <<: *e2e_test_definition

addAttractionInItinerary2Login:
  <<: *e2e_test_definition

addAttractionInItineraryLoginSt:
  <<: *e2e_test_definition

addAttractionToCartUsingBankTransferSt:
  <<: *e2e_test_definition
  
addAttractionRegionToCartSt:
  <<: *e2e_test_definition

addAttractionToCart:
  <<: *e2e_test_definition

addAttractionToCart2St:
  <<: *e2e_test_definition

addAttractionToCartLogin:
  <<: *e2e_test_definition

addAttractionToCartLoginSt:
  <<: *e2e_test_definition

addAttractionToItineraryLogin:
  <<: *e2e_test_definition

AddTwoAttractionLogin:
  <<: *e2e_test_definition

addWifiToCartUsingBankTransferSt:
  <<: *e2e_test_definition

addWifiToCartLoginSt:
  <<: *e2e_test_definition

bookAttractionInvalidLogin:
  <<: *e2e_test_definition

bookAttractionLogin:
  <<: *e2e_test_definition

bookingAttractionUsingCardCreditSt:
  <<: *e2e_test_definition

bookingWifi:
  <<: *e2e_test_definition
  
bookingWifi2Login:
  <<: *e2e_test_definition

bookinWifiLoginSt:
  <<: *e2e_test_definition

bookWifiUsingCardCreditSt:
  <<: *e2e_test_definition

cartSt:
  <<: *e2e_test_definition

chooseDestinationLogin:
  <<: *e2e_test_definition

createItinerary:
  <<: *e2e_test_definition

createItineraryLogin:
  <<: *e2e_test_definition

deleteAttractionInCartLogin:
  <<: *e2e_test_definition

editAttractionInCartLogin:
  <<: *e2e_test_definition

editItineraryLogin:
  <<: *e2e_test_definition
  
editProfile:
  <<: *e2e_test_definition
  
editProfileSt:
  <<: *e2e_test_definition

loginInvalid:
  <<: *e2e_test_definition
  
searchBarCountry:
  <<: *e2e_test_definition

searchBarCountrySt:
  <<: *e2e_test_definition

searchBarTopDest:
  <<: *e2e_test_definition
  
searchDestination:
  <<: *e2e_test_definition

searchRegion:
  <<: *e2e_test_definition

topDestinationToCartSt:
  <<: *e2e_test_definition  